// WRZT Repository — kuratierte Dateiliste
// Felder: p = Pfad (relativ zum Repo-Root), t = Titel, c = Kategorie, n = Notiz/Badge, s = Größe
const CATS = {
  manifest:   { label: "📜 Manifest & Theorie-Grundlagen", desc: "Die zentralen Übersichts- und Manifest-Dokumente." },
  herleitung: { label: "🔬 Herleitungen & Beweise", desc: "Mathematische Herleitungen einzelner Größen und Effekte." },
  kosmologie: { label: "🌌 Kosmologie", desc: "Urknall-Modelle und astrophysikalische Anwendungen." },
  formeln:    { label: "🧮 Formelsammlungen", desc: "Nachschlagewerke und Formel-Kataloge." },
  tools:      { label: "🧰 Rechner & Editoren", desc: "Interaktive Werkzeuge zum Rechnen und Editieren." },
  sim:        { label: "🌊 Simulationen & Visualisierungen", desc: "Interaktive 2D/3D-Simulationen und Labore." },
  sonstiges:  { label: "📚 Sonstiges", desc: "Nicht direkt zur WRZT gehörende oder unklare Seiten." },
  doku:       { label: "📄 Dokumente (PDF)", desc: "Exportierte PDF-Fassungen." },
  assets:     { label: "🗂️ Daten & Assets", desc: "Bilder, Skripte, JSON/Excel-Daten, Readmes — keine eigenen Seiten." },
};

const FILES = [
// ---------- MANIFEST & THEORIE ----------
{p:"WRZNT/WRZTN3.html", t:"WRZNT — größte Manifest-Fassung (116K)", c:"manifest", n:"★ Kern · kein Titel-Tag gesetzt"},
{p:"WRZNT_C/index.html", t:"WRZT – Wellenraumzeit-Theorie (poliertes Dark-Gold-Design, MathJax)", c:"manifest", n:"★ Kern · deine neueste Design-Version"},
{p:"WRZNT_Buch_JZ.html", t:"WRZT - Das vollständige Universal-Manifest", c:"manifest", n:"★ Kern"},
{p:"WRZNT/WRZNT.html", t:"WRZNT — Die Wellenraumzeit-Netz-Theorie", c:"manifest"},
{p:"WRZNT/index.html", t:"WRZNT — Die Wellenraumzeit-Netz-Theorie", c:"manifest", n:"Duplikat von WRZNT/WRZNT.html"},
{p:"WRZNT/WRZNT2.html", t:"WRZNT - Die Wellenraumzeit-Netz-Theorie (kürzere Fassung)", c:"manifest"},
{p:"WRZT_Theorie_JZ.html", t:"WRZT - Das Universal-Manifest der Wellenraumzeit", c:"manifest"},
{p:"WRZT3/WRZT_Einheits_Manifest.html", t:"WRZT - Das Einheits-Manifest (2026)", c:"manifest"},
{p:"WRZT3/WRZNT_Kreisbewegung_Undatron.html", t:"WRZNT - Herleitung & anschauliche Erklärung", c:"manifest", n:"gute Einstiegsseite"},
{p:"WRZT3/WRZT_Erweitert_v2.html", t:"WRZT Erweitert v2 (kein Titel gesetzt)", c:"manifest"},
{p:"WRZT2/manifest.html", t:"WRZNT - Die Wellenraumzeit-Netz-Theorie", c:"manifest"},
{p:"HT/t.html", t:"WRZT - Das Einheits-Manifest", c:"manifest"},
{p:"WRZT.html", t:"WRZNT | Wellenraumzeit-Netz-Theorie", c:"manifest", n:"kurze Landingpage"},
{p:"Lorenz2.html", t:"WRZT - Die Wellenraumzeit-Theorie (Kurzfassung)", c:"manifest"},
{p:"WRZT_Theorie.html", t:"WRZT - Das Trägheits-Gesetz der Wellenraumzeit", c:"manifest"},
{p:"WRZTNetz.html", t:"WRZT – Zusammenfassung", c:"manifest"},
{p:"WRZT_Calc/wrzt_zusammenfassung.html", t:"Zusammenfassung der WRZNT (mit LaTeX)", c:"manifest"},
{p:"wrzt_theorie_2.html", t:"WRZT Theorie-Seite (kurz)", c:"manifest"},

{p:"WRZT3/wrzt_berechnung_g.html", t:"Wellenraumzeit-Theorie (WRZT)", c:"manifest"},
{p:"WRZT3/Fz=Fc-Eph_2.html", t:"WRZT - Photonenradius", c:"manifest"},
{p:"WRZT3/elektron-photon-radius-3.html", t:"Elektron ↔ Photon", c:"manifest"},
{p:"WRZT3/Wellenraumzeit_Theorie_Fiat_Lux.html", t:"WRZT3 - Fiat Lux", c:"manifest"},
{p:"WRZT3/wrznt.html", t:"WRZNT", c:"manifest"},
{p:"Fiat-Lux–Einheits-Manifest.html", t:"WRZNT- Fiat Manifest", c:"manifest"},
{p:"Fiat_lux.html", t:"WRZNT - Fiat_lux", c:"manifest"},
{p:"Index_Dashboard.html", t:"Index_Dashboard", c:"manifest"},
{p:"Index.html", t:"Dieses Dasbord", c:"manifest"},
{p:"WRZT3/wrznt.html", t:"WRZNT - Frei", c:"manifest"},

// ---------- HERLEITUNGEN ----------
{p:"HT/GravitationTrägheit.html", t:"Gravitation, Trägheit und Lichtgeschwindigkeit in der Wellenraumzeit (164K)", c:"herleitung", n:"umfangreichstes Kapitel"},
{p:"HT/Wellenraumzeit.html", t:"Gravitation, Trägheit und Lichtgeschwindigkeit (92K)", c:"herleitung", n:"Duplikat/Variante von GravitationTrägheit.html"},
{p:"HT/wrzt_kapitel_gravitation_lichtgeschwindigkeit.html", t:"Gravitation, Trägheit und Lichtgeschwindigkeit (Kurzfassung)", c:"herleitung"},
{p:"HT/Traegheit.html", t:"WRZT – Trägheit", c:"herleitung"},
{p:"HT/U_Tensor.html", t:"Tensorstruktur von U_μν(z,t)", c:"herleitung"},
{p:"HT/Undatron_Formel.html", t:"Undatron-Formel (Export, 80K)", c:"herleitung"},
{p:"G-E-Welle/Wellenfeld-Gleichung.html", t:"Wellenfeld-Gleichung (100K, große Herleitung)", c:"herleitung"},
{p:"Plasmafrequenz/Wirbelströme.html", t:"Das Einheits-Manifest: Ergänzung Plasmafrequenz", c:"herleitung"},
{p:"3Rmin.html", t:"Vergleich der drei Minimalradien", c:"herleitung"},
{p:"WRZNT/Rmin_Kurve_G3.html", t:"WRZT: Dynamik der Annäherung (R_min)", c:"herleitung"},
{p:"WRZT3/WRZT_Herleitung_Rmin_LaTeX.html", t:"Herleitung R_min (LaTeX, kein Titel gesetzt)", c:"herleitung"},
{p:"WRZT2/klassischer_elektronenradius.html", t:"Herleitung des klassischen Elektronenradius", c:"herleitung"},
{p:"WRZT3/klassischer_elektronenradius.html", t:"Herleitung des klassischen Elektronenradius", c:"herleitung", n:"Duplikat von WRZT2/…"},
{p:"WRZT3/klassischer_elektronenradius_praezision.html", t:"Herleitung & Präzisionsberechnung des klassischen Elektronenradius", c:"herleitung"},
{p:"WRZT2/Spin-Herleitungen-1.html", t:"Mathematischer Vergleich der Spin-Herleitungen", c:"herleitung"},
{p:"WRZT2/Spin-Herleitungen-2.html", t:"Mathematischer Vergleich mit Zahlenwerten", c:"herleitung"},
{p:"WRZT2/Lorenz_Geo.html", t:"Tangens-Modell und Lorentz-Faktor", c:"herleitung"},
{p:"WRZT2/Lorenz_Trigo.html", t:"Der Lorentz-Faktor als Bugwelle des Raums", c:"herleitung"},
{p:"WRZT_Lorenz.html", t:"Der Lorentz-Faktor als Bugwelle des Raums", c:"herleitung", n:"Duplikat von WRZT2/Lorenz_Trigo.html"},
{p:"WRZT_Lorenz_2.html", t:"WRZT - Mathematische Herleitung", c:"herleitung"},
{p:"WRZT2/Lorenz.html", t:"Lorentz (kurz)", c:"herleitung"},
{p:"WRZT3/WRZT_Trans.html", t:"Mathematischer Beweis der Transversalwelle", c:"herleitung"},
{p:"WRZT2/Elektrodynamische-Kopplung.html", t:"Das Einheits-Manifest: Elektrodynamische Kopplung", c:"herleitung"},
{p:"WRZT2/Magnetische-Feldkonstante.html", t:"Magnetische Feldkonstante (kein Titel gesetzt)", c:"herleitung"},
{p:"WRZT2/Magnetische-Feldkonstante2.html", t:"Elektrodynamische Kopplung & Magnetismus", c:"herleitung"},
{p:"WRZT2/Kopplung des Elektrons.html", t:"Das Einheits-Manifest: Kapitel Elektron-Resonanz", c:"herleitung"},
{p:"WRZT2/Lichtbrechung.html", t:"Das Einheits-Manifest: Die Lichtbrechung", c:"herleitung"},
{p:"WRZT2/Lichtbrechung2.html", t:"Die Lichtbrechung (Variante 2)", c:"herleitung"},
{p:"WD.html", t:"DFRT & WRZT – Feld, Raumzeit und Licht", c:"herleitung", n:"Nebentheorie DFRT"},
{p:"WRZT3/ZentriCoulomb.html", t:"Zentrifugalkraft vs. Coulomb-Kraft", c:"herleitung"},
{p:"WRZT3/Undatron.html", t:"Annihilation, Undatron und Wellenraumzeit-Mechanismus", c:"herleitung"},
{p:"WRZT3/Kreisbewegung_Fundamentale_Wechselwirkungen.html", t:"Kreisbewegung mit fundamentalen Wechselwirkungen", c:"herleitung"},
{p:"WRZT3/WRZT_Alpha.html", t:"Feinstrukturkonstante α (Export, 64K)", c:"herleitung"},
{p:"WRZT3/WRZT_Interferenz.html", t:"Interferenz (Export, 32K)", c:"herleitung"},
{p:"WRZT2/milestone-geometrie.html", t:"WRZT - Milestone Geometrie", c:"herleitung"},
{p:"LWT.html", t:"LWT Labor v10 - Unified Theory", c:"herleitung", n:"Nebentheorie: Lorentz-Wand-Theorie"},
{p:"LWT_Def.html", t:"Das offizielle Manifest der Lorentz-Wand-Theorie", c:"herleitung", n:"Nebentheorie LWT"},

// ---------- KOSMOLOGIE ----------
{p:"WRZT2/urknall.html", t:"1. Ausgangspunkt der WRZT (Urknall, 72K)", c:"kosmologie"},
{p:"WRZT2/urknall-LKM.html", t:"Lebender-Kosmos-Modell", c:"kosmologie"},
{p:"WRZT3/WRZT_Urknall.html", t:"Kosmologische Phase & Urknall", c:"kosmologie"},
{p:"WRZT2/Urknall2.html", t:"Kosmologisches Gesamtmodell", c:"kosmologie"},
{p:"astro_physform.html", t:"AstroPhysForm · WRZT · WRZNT (76K)", c:"kosmologie"},

// ---------- FORMELSAMMLUNGEN ----------
{p:"WRZT_Formelsammlung.html", t:"WRZT / WRZNT – Formelsammlung (44K)", c:"formeln", n:"★ umfangreichste Sammlung"},
{p:"formel_sammler_pro.html", t:"WRZT - Universeller Formelsammlung Generator", c:"formeln"},
{p:"formel_sammler.html", t:"WRZT - Automatische Formelsammlung", c:"formeln"},
{p:"WRZT3/WRZT_Formelsammlung_b.html", t:"Formelsammlung B (kein Titel gesetzt)", c:"formeln"},
{p:"WRZT3/WRZT_LaTeX_Katalog.html", t:"LaTeX-Katalog (kein Titel gesetzt)", c:"formeln"},
{p:"WRZT3/WRZT_Praezision_Katalog.html", t:"Präzisions-Katalog (kein Titel gesetzt)", c:"formeln"},
{p:"WRZT2/Formelsammlungs-Kartei/index.html", t:"WRZNT 2 - Formelsammlung (Karteikarten-Tool)", c:"formeln"},
{p:"trigonometrie_formeln.html", t:"Wichtige Trigonometrie-Formeln", c:"formeln"},
{p:"W_Formeln_A.html", t:"W_Formeln_styled", c:"formeln"},
{p:"WRZT_Calc/alpha-Formeln.html", t:"Alpha-Formeln (kein Titel gesetzt)", c:"formeln"},

// ---------- TOOLS / RECHNER ----------
{p:"WRZT_Calc/index.html", t:"Physik Formelrechner", c:"tools", n:"★ dein neuester Rechner (LaTeX-Eingabe, Konstanten)"},
{p:"WRZT2/Latex-Rechner-Cl/index.html", t:"Physik Rechner — Formel-Editor", c:"tools"},
{p:"physik_formel_editor.html", t:"PhysForm · Physikalischer Formeleditor", c:"tools"},
{p:"G-E-Welle/MD_Editor.html", t:"WRZT - Ultimate Readme.md Live Editor", c:"tools"},

// ---------- SIMULATIONEN ----------
{p:"HT/index.html", t:"WRZNT 3D Wellennetz mit Doppelspalt", c:"sim"},
{p:"HT/wave_double_slit.html", t:"WRZNT 3D Wellennetz mit Doppelspalt", c:"sim"},
{p:"HT/wave_double_slit_f.html", t:"WRZNT 3D Wellennetz mit Doppelspalt", c:"sim", n:"Duplikat"},
{p:"wave_double_slit_f.html", t:"WRZNT 3D Wellennetz mit Doppelspalt", c:"sim", n:"Duplikat von HT/"},
{p:"HT/wave-net-simulation.html", t:"WRZNT 3D Wellennetz-Simulation", c:"sim"},
{p:"HT/wave-net-simulation (9).html", t:"WRZNT 3D Wellennetz-Simulation (Rev. 9)", c:"sim"},
{p:"wave-net-simulation (9).html", t:"WRZNT 3D Wellennetz-Simulation (Rev. 9)", c:"sim", n:"Duplikat von HT/"},
{p:"HT/wrznt_enhanced(3D).html", t:"WRZNT – 3D Netzwerksimulation", c:"sim"},
{p:"wrznt_enhanced(3D).html", t:"WRZNT – 3D Netzwerksimulation", c:"sim", n:"Duplikat von HT/"},
{p:"HT/wrznt_ladund.html", t:"WRZNT – Netzwerksimulation", c:"sim"},
{p:"wrznt_ladund.html", t:"WRZNT – Netzwerksimulation", c:"sim", n:"Duplikat von HT/"},
{p:"HT/wrznt_netzwerk_simulation.html", t:"WRZNT — Netzwerksimulation (Undatrone)", c:"sim"},
{p:"wrznt_netzwerk_simulation.html", t:"WRZNT — Netzwerksimulation (Undatrone)", c:"sim", n:"Duplikat von HT/"},
{p:"HT/wrznt_netzwerk_simulation_3d.html", t:"WRZNT — 3D Netzwerksimulation (Undatrone)", c:"sim"},
{p:"wrznt_netzwerk_simulation_3d.html", t:"WRZNT — 3D Netzwerksimulation (Undatrone)", c:"sim", n:"Duplikat von HT/"},
{p:"HT/spiral_undatron.html", t:"WRZNT - Interferierende Wirbel-Wellen", c:"sim"},
{p:"HT/spiral_undatron (Kopie).html", t:"WRZNT - 3D Spiral Vortex Interferenz", c:"sim", n:"Kopie"},
{p:"HT/photon2(1).html", t:"Undatron-Labor 1/9 — Annäherung & Emission", c:"sim", n:"Serie"},
{p:"HT/photon2(2).html", t:"Undatron-Labor 2/9 — Interaktive Simulation", c:"sim", n:"Serie"},
{p:"HT/photon2(2D).html", t:"Undatron-Labor — Annihilation & Übergang (2D)", c:"sim", n:"Serie"},
{p:"HT/photon2(3).html", t:"Undatron-Labor 3/9 — Labor: Undatron & r_min", c:"sim", n:"Serie"},
{p:"HT/photon2(3D).html", t:"Undatron-Labor — 3D Heatmap-Netz", c:"sim", n:"Serie"},
{p:"HT/photon2(3D) (2).html", t:"Undatron-Labor — Helikales Undatron (Spiralwelle)", c:"sim", n:"Serie"},
{p:"HT/photon2(3D) (3).html", t:"Undatron-Labor — Labor-Konsole", c:"sim", n:"Serie"},
{p:"HT/photon2(4).html", t:"Undatron-Labor 4/9 — Amplitudensteuerung", c:"sim", n:"Serie"},
{p:"Undatron_3D.html", t:"Undatron 3D – Raumzeit-Wellen & Lorentz-Kraft", c:"sim"},
{p:"GWelle3D.html", t:"WRZT – Quadrupol-Welle", c:"sim"},
{p:"Kugel(5).html", t:"WRZT - Interaktives Vektorfeld Dipolquelle", c:"sim"},
{p:"Lorentz-Wand.html", t:"WRZNT - Labor v4 (Pause & Dualität)", c:"sim"},
{p:"Lorentz-Wand(2).html", t:"LWT Labor v6 - Multi-Teilchen Interaktion", c:"sim"},
{p:"WRZNT/Quanten-Spin-Raumwirbel.html", t:"WRZT - Raumwirbel Simulation", c:"sim"},
{p:"WRZNT/Quanten-Spin-Raumwirbel-3d.html", t:"WRZT - Interaktiver 3D Raumwirbel", c:"sim"},
{p:"WRZNT/Raumwirbel.html", t:"Raumwirbel (40K)", c:"sim"},
{p:"WRZT2/Topologischer-3D-Raumwirbel.html", t:"WRZT - Interaktiver 3D Raumwirbel", c:"sim"},
{p:"WRZT2/Raumzeit-Feldwirbel.html", t:"Raumzeit-Feldwirbel (kein Titel gesetzt)", c:"sim"},
{p:"WRZNT/curve3d.html", t:"3D Kurve im Kubus", c:"sim"},
{p:"WRZNT/curve3d-1.html", t:"3D Kurve im Kubus (Variante, 40K)", c:"sim"},
{p:"WRZNT/sinus-cube-3d.html", t:"WRZT · 3D (Sinus-Kubus)", c:"sim"},
{p:"G-E-Welle/G-E-Welle-1.html", t:"WRZNT - Wellen-Interferenz Simulator", c:"sim"},
{p:"G-E-Welle/G-E-Welle-2.html", t:"WRZNT - Wellen-Interferenz & Quellen", c:"sim"},
{p:"G-E-Welle/index.html", t:"Welleninterferenz · 2D Schirm", c:"sim"},
{p:"G-E-Welle/Wellenfeld-Sim.html", t:"WRZT - Bugwellen Simulation (Expansion)", c:"sim"},
{p:"Wellen_1(1)(1).html", t:"3D Wellenfeld", c:"sim"},
{p:"wrzt_rmin.html", t:"R_min-Simulation — Variante 1/4", c:"sim"},
{p:"wrzt_rmin1.html", t:"R_min-Simulation — Variante 2/4", c:"sim"},
{p:"wrzt_rmin2.html", t:"R_min-Simulation — Variante 3/4", c:"sim"},
{p:"wrzt_rmin3.html", t:"R_min-Simulation — Variante 4/4", c:"sim"},
{p:"wrztbugwelle.html", t:"WRZT - Bugwelle", c:"sim"},

// ---------- SONSTIGES ----------
{p:"Lisa.html", t:"3D Lissajous-Figuren", c:"sonstiges", n:"⚠️ aktuell die GitHub-Pages-Startseite"},
{p:"LisaK.html", t:"3D Lissajous-Figuren K", c:"sonstiges", n:"Duplikat von Lisa.html"},
{p:"Physiker.html", t:"Große Physiker & Physikerinnen ab 1700", c:"sonstiges"},
{p:"WRZT2/ico.html", t:"Meine Astronomie Seite", c:"sonstiges"},
{p:"WRZT2/dreieck.html", t:"Dreieck-Testseite (kein Titel gesetzt)", c:"sonstiges"},
{p:"HT/t2.html", t:"Links", c:"sonstiges"},
{p:"yout.html", t:"ohne Titel — Inhalt unklar", c:"sonstiges"},

// ---------- DOKUMENTE ----------
{p:"WRZNT .pdf", t:"WRZNT — PDF-Export", c:"doku"},
{p:"wrzt_theorie.pdf", t:"WRZT Theorie — PDF-Export", c:"doku"},

// ---------- DATEN & ASSETS ----------
{p:"README.md", t:"README (mit deinem eigenen Struktur-Vorschlag!)", c:"assets"},
{p:"zen-links.json", t:"zen-links.json", c:"assets"},
{p:"favicon.png", t:"favicon.png", c:"assets"},
{p:"titelbild.jpeg", t:"titelbild.jpeg", c:"assets"},
{p:"QW.png", t:"QW.png", c:"assets"},
{p:".github/workflows/deploy.yml", t:"GitHub-Pages Deploy-Workflow", c:"assets"},
{p:"G-E-Welle/Readme.md", t:"Readme (G-E-Welle)", c:"assets"},
{p:"G-E-Welle/script.js", t:"script.js (G-E-Welle)", c:"assets"},
{p:"G-E-Welle/style.css", t:"style.css (G-E-Welle)", c:"assets"},
{p:"HT/script.js", t:"script.js (HT)", c:"assets"},
{p:"HT/styles.css", t:"styles.css (HT)", c:"assets"},
{p:"Plasmafrequenz/wirbelströme.py", t:"wirbelströme.py", c:"assets"},
{p:"Plasmafrequenz/wirbelströme_1.py", t:"wirbelströme_1.py", c:"assets"},
{p:"Plasmafrequenz/Screenshot 2026-07-18 152209.png", t:"Screenshot (Plasmafrequenz)", c:"assets"},
{p:"Plasmafrequenz/Screenshot 2026-07-18 152341.png", t:"Screenshot (Plasmafrequenz)", c:"assets"},
{p:"WRZNT/images/image1.png", t:"image1.png (WRZNT)", c:"assets"},
{p:"WRZNT/kurven_formeln.xlsx", t:"kurven_formeln.xlsx — Excel-Datenbasis", c:"assets"},
{p:"WRZNT_C/script.js", t:"script.js (WRZNT_C)", c:"assets"},
{p:"WRZNT_C/script (Kopie).js", t:"script.js — Kopie (WRZNT_C)", c:"assets", n:"Kopie"},
{p:"WRZNT_C/styles.css", t:"styles.css (WRZNT_C)", c:"assets"},
{p:"WRZNT_C/titelbild.jpeg", t:"titelbild.jpeg (WRZNT_C)", c:"assets"},
{p:"WRZT2/Formelsammlungs-Kartei/script.js", t:"script.js (Formelsammlungs-Kartei)", c:"assets"},
{p:"WRZT2/Formelsammlungs-Kartei/style.css", t:"style.css (Formelsammlungs-Kartei)", c:"assets"},
{p:"WRZT2/Formelsammlungs-Kartei/wrznt2_formula_collection.json", t:"wrznt2_formula_collection.json — Formeldaten", c:"assets"},
{p:"WRZT2/Latex-Rechner-Cl/script.js", t:"script.js (Latex-Rechner-Cl)", c:"assets"},
{p:"WRZT2/Latex-Rechner-Cl/style.css", t:"style.css (Latex-Rechner-Cl)", c:"assets"},
{p:"WRZT2/Lorenz.md", t:"Lorenz.md", c:"assets"},
{p:"WRZT2/favicon.png", t:"favicon.png (WRZT2)", c:"assets"},
{p:"WRZT2/logo.svg", t:"logo.svg (WRZT2)", c:"assets"},
{p:"WRZT_Calc/Physik.jpeg", t:"Physik.jpeg", c:"assets"},
{p:"WRZT_Calc/alpha.py", t:"alpha.py", c:"assets"},
{p:"WRZT_Calc/logo.png", t:"logo.png (WRZT_Calc)", c:"assets"},
{p:"WRZT_Calc/physik_formeln_2026-07-24.json", t:"physik_formeln_2026-07-24.json — Konstanten/Formeln", c:"assets"},
{p:"WRZT_Calc/readme.md", t:"readme.md (WRZT_Calc)", c:"assets"},
{p:"WRZT_Calc/script.js", t:"script.js (WRZT_Calc)", c:"assets"},
{p:"WRZT_Calc/style.css", t:"style.css (WRZT_Calc)", c:"assets"},
];
